version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.23.1

jobs:
  push_latest_version_tag:
    docker:
      - image: circleci/ruby:2.6
    working_directory: ~/app
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "97:c5:a4:96:21:e0:d8:97:31:7a:c6:c6:42:09:d1:0f"
      - run: curl -fLSs https://circle.ci/cli | sudo bash
      - run:
          name: Setup git
          command: |
            git config push.default current
            git config user.email "$EMAIL"
            git config user.name "CircleCI"
      - run: ruby .circleci/push_latest_version_tag.rb sue445/codeclimate

workflows:
  version: 2

  build:
    jobs:
      - orb-tools/pack:
          source-dir: src/
          destination-orb-path: packed/orb.yml
          workspace-path: packed/orb.yml
          artifact-path: packed/orb.yml

      - orb-tools/test-in-builds:
          orb-location: packed/orb.yml
          orb-name: codeclimate
          test-steps:
            - orb-tools/local-test-build:
                test-config-location: test/with-cc-test-reporter_test.yml
          attach-workspace: true
          checkout: true
          workspace-root: /home/circleci/project/
          requires:
            - orb-tools/pack

      - orb-tools/increment:
          orb-path: packed/orb.yml
          orb-ref: "sue445/codeclimate"
          segment: "patch"
          publish-token-variable: "$CIRCLECI_API_TOKEN"
          attach-workspace: true
          checkout: false
          requires: [orb-tools/test-in-builds]
          filters:
            branches:
              only: master

      - push_latest_version_tag:
          requires: [orb-tools/increment]
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/

  release:
    jobs:
      - orb-tools/pack:
          source-dir: src/
          destination-orb-path: packed/orb.yml
          workspace-path: packed/orb.yml
          artifact-path: packed/orb.yml
          filters:
            tags:
              only: /^[0-9.]+\.0$/
            branches:
              ignore: /.*/

      - orb-tools/publish:
          orb-path: packed/orb.yml
          orb-ref: "sue445/ruby-orbs@${CIRCLE_TAG}"
          publish-token-variable: "$CIRCLECI_API_TOKEN"
          attach-workspace: true
          checkout: false
          requires: [orb-tools/pack]
          filters:
            tags:
              only: /^[0-9.]+\.0$/
            branches:
              ignore: /.*/
